### ISSUE TITLE
Fix Jumbotron

### ISSUE THREAD

**Issue by sebo2233** [sebo2233/archives-and-creative-writing#4]
1. Figure out how to get rid of background color (already tried hashing out that line of the css)
2. Make sure uploaded img appears properly

**Comment by sebo2233** [comment]
I tried deleting the entire line of the css  but that also didn't help. I think I need to choose an image for the background to make it work, otherwise it will just fill in the original color to fill the empty space

**Comment by sebo2233** [comment]
i tried uploading a jpg version and a png version to the img folder for the background (stacks-l.jpg and stacks-l.png), and neither image worked when I tried to put them in the _config.yml file in the jumbotron_image line. @chrisdaaz any change you'd have advice for this issue?

**Comment by chrisdaaz** [comment]
@sebo2233 i see the .png image here: https://sebo2233.github.io/archives-and-creative-writing/

is that not the image you want as the background?

**Comment by sebo2233** [comment]
Oh man, I think it just took longer than normal so I didn’t see it on the site. Sorry for the unnecessary tag!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
